Improved wording and added auto-release (#22)
* Improved wording for Workflows git chapter

* Testing release

* Fixed mdlint

* Updating version

* Fixing release

* Updating version

* Updating version

* Fixing release

* New method for release

* Updated wording

* Updating release CI

* Updating release CI

* Fixing git diff

* Updated CI strategy

* Fixing release

* Fixing release

* Fixing release

* Fixing release

* Fixing release

* Fixing release

* Fixing release

* Updated version

* Minimized name of step

* Updated version

* Removed mention of release branch

diff --git a/.github/workflows/render.yml b/.github/workflows/render.yml
--- a/.github/workflows/render.yml
+++ b/.github/workflows/render.yml
@@ -90,9 +90,9 @@ jobs:
   #
   # When badly referenced, pandoc generates a double questionmarks ("??") in the place
   # of the latex tags. This Action checks if there are no "??" in the generated PDF.
-  check_picture_references:
+  check_latex_references:
     needs: render-book
-    name: Check valid latex references for pictures
+    name: Check valid latex references
     runs-on: ubuntu-22.04
     steps:
     - name: Check out code
@@ -135,9 +135,10 @@ jobs:
           echo "The file does not contain the string '??'"
         fi
 
-  deploy-to-gh-pages:
+
+  deploy_to_gh_pages:
     if: github.ref == 'refs/heads/main'
-    needs: render-book
+    needs: check_latex_references
     runs-on: ubuntu-22.04
     name: Deploy to GitHub Pages
 
@@ -172,3 +173,87 @@ jobs:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: output/
         full_commit_message: Publishing version ${{ env.BOOK_VERSION }} - ${{ github.event.head_commit.message }}
+        cname: book-devops.berwick.fr
+
+
+  check_version_change:
+    name: "Check version change"
+    runs-on: ubuntu-22.04
+    needs: check_latex_references
+    outputs:
+      version_changed: ${{ steps.check.outputs.version_changed }}
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          ref: ${{ github.sha }}
+          fetch-depth: 2
+
+      - name: Get Previous Commit
+        id: prev_commit
+        run: echo "::set-output name=sha::$(git log --skip=1 -n 1 --pretty=format:'%H')"
+
+      - name: Check VERSION file change
+        id: check
+        run: |
+          if git diff --name-only ${{ steps.prev_commit.outputs.sha }} ${{ github.sha }} | grep '^VERSION$'; then
+            echo "VERSION file was modified."
+            echo "::set-output name=version_changed::true"
+          else
+            echo "VERSION file was not modified."
+            echo "::set-output name=version_changed::false"
+          fi
+
+
+  release:
+    if: needs.check_version_change.outputs.version_changed == 'true' && (github.ref == 'refs/heads/main')
+    needs: check_version_change
+    runs-on: ubuntu-22.04
+    name: Generate book files for release
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: Get version
+      run: |
+        version=$(cat ./VERSION)
+        version=${version##+( )} # Trim left whitespaces
+        version=${version%%+( )} # Trim right whitespaces
+        echo "BOOK_VERSION=$version" >> $GITHUB_ENV
+        echo "version : $version"
+    - name: Checking version format
+      run: |
+        if ! [[ $BOOK_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)(-[0-9]+)?)?$ ]]
+        then
+          echo "Invalid version format. Check your ./VERSION file."
+          exit 1
+        fi
+
+    - name: Download PDF artifact
+      uses: actions/download-artifact@v3
+      with:
+        name: book-pdf-${{ env.BOOK_VERSION }}
+        path: ./
+
+    - name: Get version
+      id: get-version
+      run: |
+        VERSION_CONTENT=$(cat VERSION)
+        echo "::set-output name=version::$VERSION_CONTENT"
+        if [[ $VERSION_CONTENT == *"-alpha"* ]]; then
+          echo "::set-output name=prerelease::true"
+        else
+          echo "::set-output name=prerelease::false"
+        fi
+
+    - name: Create release
+      uses: softprops/action-gh-release@v1
+      with:
+        name: ${{ env.BOOK_VERSION }}
+        tag_name: ${{ env.BOOK_VERSION }}
+        files: |
+          ./book.pdf
+        prerelease: ${{ steps.get-version.outputs.prerelease }}
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
